# Generated by Django 4.1 on 2022-08-22 16:06

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_token_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=accounts.models.gen_uuid, max_length=40),
        ),
    ]
